#!/bin/bash

sbatch -J "chr_1" analysis_10m_snps/data_preparation/compute_ld_job.sh "1"
sbatch -J "chr_2" analysis_10m_snps/data_preparation/compute_ld_job.sh "2"
sbatch -J "chr_3" analysis_10m_snps/data_preparation/compute_ld_job.sh "3"
sbatch -J "chr_4" analysis_10m_snps/data_preparation/compute_ld_job.sh "4"
sbatch -J "chr_5" analysis_10m_snps/data_preparation/compute_ld_job.sh "5"
sbatch -J "chr_6" analysis_10m_snps/data_preparation/compute_ld_job.sh "6"
sbatch -J "chr_7" analysis_10m_snps/data_preparation/compute_ld_job.sh "7"
sbatch -J "chr_8" analysis_10m_snps/data_preparation/compute_ld_job.sh "8"
sbatch -J "chr_9" analysis_10m_snps/data_preparation/compute_ld_job.sh "9"
sbatch -J "chr_10" analysis_10m_snps/data_preparation/compute_ld_job.sh "10"
sbatch -J "chr_11" analysis_10m_snps/data_preparation/compute_ld_job.sh "11"
sbatch -J "chr_12" analysis_10m_snps/data_preparation/compute_ld_job.sh "12"
sbatch -J "chr_13" analysis_10m_snps/data_preparation/compute_ld_job.sh "13"
sbatch -J "chr_14" analysis_10m_snps/data_preparation/compute_ld_job.sh "14"
sbatch -J "chr_15" analysis_10m_snps/data_preparation/compute_ld_job.sh "15"
sbatch -J "chr_16" analysis_10m_snps/data_preparation/compute_ld_job.sh "16"
sbatch -J "chr_17" analysis_10m_snps/data_preparation/compute_ld_job.sh "17"
sbatch -J "chr_18" analysis_10m_snps/data_preparation/compute_ld_job.sh "18"
sbatch -J "chr_19" analysis_10m_snps/data_preparation/compute_ld_job.sh "19"
sbatch -J "chr_20" analysis_10m_snps/data_preparation/compute_ld_job.sh "20"
sbatch -J "chr_21" analysis_10m_snps/data_preparation/compute_ld_job.sh "21"
sbatch -J "chr_22" analysis_10m_snps/data_preparation/compute_ld_job.sh "22"
